
CREATE TABLE game (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  tagline VARCHAR(255) NOT NULL,
  overview TEXT NOT NULL,
  illustration VARCHAR(255) NOT NULL, 
  background VARCHAR(255),
  player VARCHAR(10) NOT NULL,
  duration INT NOT NULL,
  age VARCHAR(4) NOT NULL,
  duo BOOLEAN NOT NULL
);

CREATE TABLE user(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pseudo VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'user'
);